apiVersion: v1
kind: Service
metadata:
  name: sponspay-webapp-service
  labels:
    app: sponspay-webapp
    component: frontend
spec:
  selector:
    app: sponspay-webapp
  type: NodePort
  ports:
    - port: 80
      targetPort: http
      name: http
