apiVersion: v1
kind: ConfigMap
metadata:
  name: iap-access-policy
  namespace: sponspay-dev
data:
  policy.yaml: |
    bindings:
    - members:
      - domain:sponspay.com
      role: roles/iap.httpsResourceAccessor
    etag: ABCD
    version: 1
