apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: sponspay-webapp-dev

namespace: sponspay-dev

resources:
  - ../../base
  - ingress.yaml
  - managedcertificate.yaml
  - namespace.yaml
  - backendconfig-patch.yaml
  - iap-policy.yaml

patches:
- path: deployment-patch.yaml
- path: service-patch.yaml

images:
  - name: us-east1-docker.pkg.dev/sponspay-deployment/sponspay-dev/webapp
    newTag: dev-latest

namePrefix: dev-
