apiVersion: networking.gke.io/v1
kind: ManagedCertificate
metadata:
  name: dev-sponspay-api-cert
  namespace: sponspay-api-dev
  labels:
    environment: development
spec:
  domains:
  - api-dev.sponspay.com
