apiVersion: networking.gke.io/v1beta1
kind: FrontendConfig
metadata:
  name: redisinsight-frontendconfig
  namespace: sponspay-api-dev
  labels:
    environment: development
spec:
  redirectToHttps:
    enabled: true
    responseCodeName: MOVED_PERMANENTLY_DEFAULT
