#!/usr/bin/env bash
set -euo pipefail

# Usage:
#   ./make-dotenv.sh [output_env_file]
# Default output is ".env" in the current directory.
#
# This script reads specific environment variables from the current shell
# and writes them to a .env file as KEY="value".
# It converts actual newlines in values to literal \n so the .env stays one-line-per-key.
# Missing variables are noted as comments and not written as empty values.

ENV_FILE="${1:-.env}"

# List of variables to capture (includes NODE_ENV per your example)
VARS=(
  NODE_ENV
  ZOHO_REFRESH_TOKEN
  TELEGRAM_SESSION_STRING
  TELEGRAM_API_HASH
  ZOHO_CLIENT_SECRET
  SENDGRID_API_KEY
  TELEGRAM_API_ID
  SERVICE_ACCOUNT_PRIVATE_KEY
  FIREBASE_SERVICE_ACCOUNT
  ZOHO_CLIENT_ID
  SERVICE_ACCOUNT
)

escape_for_dotenv() {
  # Convert CRLF to LF, then real newlines to \n, and escape double quotes.
  # We do NOT escape backslashes so sequences like \n remain unchanged if already present.
  # This keeps common patterns like replacing \\n with \n in app code working as intended.
  local v
  v="$(printf '%s' "$1" | sed -e ':a;N;$!ba;s/\r//g' -e 's/\n/\\n/g' -e 's/"/\\"/g')"
  printf '%s' "$v"
}

# Ensure target directory exists
env_dir="$(dirname "$ENV_FILE")"
mkdir -p "$env_dir"

# Create temp file in the same directory for atomic move
tmp_file="$(mktemp "${env_dir}/.env.tmp.XXXXXX")"

{
  echo "# Autogenerated by make-dotenv.sh on $(date -u +\"%Y-%m-%dT%H:%M:%SZ\")"
  echo "# Values sourced from current shell environment"
  echo
} > "$tmp_file"

missing=()

for key in "${VARS[@]}"; do
  if [[ -n "${!key:-}" ]]; then
    escaped_val="$(escape_for_dotenv "${!key}")"
    printf '%s="%s"\n' "$key" "$escaped_val" >> "$tmp_file"
  else
    missing+=("$key")
    printf '# %s is not set in the environment\n' "$key" >> "$tmp_file"
    printf '# %s=\n' "$key" >> "$tmp_file"
  fi
done

# Restrict permissions and move atomically into place
chmod 600 "$tmp_file"
mv "$tmp_file" "$ENV_FILE"

# Final status message
if (( ${#missing[@]} > 0 )); then
  echo "Wrote $ENV_FILE with missing variables commented out: ${missing[*]}" >&2
else
  echo "Wrote $ENV_FILE with all variables present."
fi
